watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: false
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 37
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
        - glazewm_workspaces
        - separator
        - media
      center:
        - clock
      right:
        - systray
        - separator
        - volume
        - battery
        - separator
        - notifications
widgets:
  separator:
    type: "yasb.custom.CustomWidget"
    options:
      class_name: "separator"
      label: "|"
      label_alt: "|"
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: false
      animation: false

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      hide_empty: true
      max_field_size:
        label: 30
      show_thumbnail: false
      controls_hide: true
      media_menu:
        blur: false
        round_corners: false
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 4
        thumbnail_corner_radius: 0
        thumbnail_size: 120
        max_title_size: 50
        max_artist_size: 20
        show_source: false
      media_menu_icons:
        play: "󰐊"
        pause: "󰏤"
        prev_track: "󰒮"
        next_track: "󰒭"
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_play_pause"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M}"
      label_alt: "{%A, %d/%m/%Y - %I:%M %p}"
      update_interval: 1000
      tooltip: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "◀"
      label_expanded: "▶"
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{level}"
      tooltip: false
      slider_beep: false
      progress_bar:
        enabled: true
        position: "left"
        size: 16
        thickness: 4
        color: "#E67E80"
        background_color: "#4F5B58"
        animation: true
      audio_menu:
        blur: false
        round_corners: false
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 4
        # show_apps: true
        # show_app_labels: true
        # show_app_icons: true
        # show_apps_expanded: false
        # app_icons:
        #   toggle_down: "▼"
        #   toggle_up: "▲"
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "do_nothing"
        on_right: "toggle_mute"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: false
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "󱐋"
        icon_critical: "󰂎"
        icon_low: "󱊡"
        icon_medium: "󱊢"
        icon_high: "󱊣"
        icon_full: "󱊣"
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>󰂚 </span>{count}"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_middle: "do_nothing"
        on_right: "clear_notifications"
